{{- if not (empty .Values.secrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: cannon
  labels:
    app: cannon
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- with .Values.secrets }}
  rabbitmqUsername: {{ .rabbitmq.username | b64enc | quote }}
  rabbitmqPassword: {{ .rabbitmq.password | b64enc | quote }}
  {{- end }}
{{- end }}
