# This helmfile is similar to the 'helmfile.yaml', but only spawns up components for a single backend.
# In some situations (when not testing anything federation specific), use of a single backend is sufficient.
#
# The 'make kube-integration-setup-sans-federation' target uses this helmfile.

helmDefaults:
  wait: true
  timeout: 600
  devel: true

environments:
  default:
    values:
      - namespace: {{ requiredEnv "NAMESPACE" }}
      - federationDomain: {{ requiredEnv "FEDERATION_DOMAIN" }}
      - ingressChart: {{ requiredEnv "INGRESS_CHART" }}
      - imagePullPolicy: Always
      - redisStorageClass: hcloud-volumes

repositories:
  - name: stable
    url: 'https://charts.helm.sh/stable'

  - name: bitnami
    url: 'https://charts.bitnami.com/bitnami'

releases:
  - name: '{{ .Values.namespace }}-ic'
    namespace: '{{ .Values.namespace }}'
    chart: '../.local/charts/{{ .Values.ingressChart }}'
    values:
      - './helm_vars/{{ .Values.ingressChart }}/values.yaml.gotmpl'

  - name: '{{ .Values.namespace }}-i'
    namespace: '{{ .Values.namespace }}'
    chart: '../.local/charts/nginx-ingress-services'
    values:
      - './helm_vars/nginx-ingress-services/values.yaml.gotmpl'
      - './helm_vars/nginx-ingress-services/certificates-namespace1.yaml'
    set:
      # Federation domain is also the SRV record created by the
      # federation-test-helper service. Maybe we can find a way to make these
      # differ, so we don't make any silly assumptions in the code.
      - name: config.dns.federator
        value: {{ .Values.federationDomain }}
    needs:
      - '{{ .Values.namespace }}-ic'
