apiVersion: v1
kind: Secret
metadata:
  name: integration
  labels:
    app: integration
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- with .Values.secrets }}
  {{- if hasKey . "uploadXmlAwsAccessKeyId" }}
  uploadXmlAwsAccessKeyId: {{ .uploadXmlAwsAccessKeyId | b64enc | quote }}
  {{- end }}
  {{- if hasKey . "uploadXmlAwsSecretAccessKey" }}
  uploadXmlAwsSecretAccessKey: {{ .uploadXmlAwsSecretAccessKey | b64enc | quote }}
  {{- end }}
  {{- end }}
