{{- if not (empty .Values.secrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: gundeck
  labels:
    app: gundeck
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- with .Values.secrets }}
  {{- if hasKey . "awsKeyId" }}
  awsKeyId: {{ .awsKeyId | b64enc | quote }}
  {{- end }}
  {{- if hasKey . "awsSecretKey" }}
  awsSecretKey: {{ .awsSecretKey | b64enc | quote }}
  {{- end }}
  rabbitmqUsername: {{ .rabbitmq.username | b64enc | quote }}
  rabbitmqPassword: {{ .rabbitmq.password | b64enc | quote }}
  {{- end }}
{{- end }}
