# The following ports must match the ports used in wire-server
#
# The sslCert strings must be replaced by real values, and the
# corresponding certificates uploaded, see
# https://aws.amazon.com/premiumsupport/knowledge-center/import-ssl-certificate-to-iam/
#

ingress:
  webapp:
    https:
      externalPort: 443
      sslCert: arn:aws:iam::00000-accountnumber-00000:server-certificate/default.domain
      sslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01
      hostname: webapp.default.domain
      ttl: 300
    http:
      webappPort: 8080
  nginz:
    https:
      externalPort: 443
      sslCert: arn:aws:iam::00000-accountnumber-00000:server-certificate/default.domain
      sslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01
      hostname: nginz-https.default.domain
      ttl: 300
    http:
      httpPort: 8080
    wss:
      externalPort: 443
      sslCert: arn:aws:iam::00000-accountnumber-00000:server-certificate/default.domain
      sslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01
      hostname: nginz-ssl.default.domain
      ttl: 300
    ws:
      wsPort: 8081
  s3minio:
    enabled: false # set to true if you wish to use minio on AWS instead of using real S3
    https:
      externalPort: 443
      sslCert: arn:aws:iam::00000-accountnumber-00000:server-certificate/default.domain
      sslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01
      hostname: assets.default.domain
      ttl: 300
    http:
      s3Port: 9000
    selector:
      key: app
      value: minio # (currently) fake-aws-s3 chart uses 'minio', minio-external chart uses 'minio-external'
  teamSettings:
    https:
      externalPort: 443
      sslCert: arn:aws:iam::00000-accountnumber-00000:server-certificate/default.domain
      sslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01
      hostname: teams.default.domain
      ttl: 300
    http:
      teamSettingsPort: 8080
  accountPages:
    https:
      externalPort: 443
      sslCert: arn:aws:iam::00000-accountnumber-00000:server-certificate/default.domain
      sslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01
      hostname: account.default.domain
      ttl: 300
    http:
      accountPagesPort: 8080
